version: "3.9"

services:

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: rice_fastapi

    ports:
      - "8000:8000"

    volumes:
      - .:/app

    restart: unless-stopped


  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: rice_mlflow

    command: mlflow ui --host 0.0.0.0 --port 5000

    ports:
      - "5000:5000"

    volumes:
      - ./mlruns:/mlruns

    restart: unless-stopped
